Prevent docker volume in use error
When running script/docker/setup on a second run, it was possible that previous containers existed as stopped but weren't removed. This caused an error where the new container couldn't be started due to the volume being reused.

We now remove orphaned containers.

```
$ docker-compose down -v
WARNING: Found orphan containers (rails-template_test-db_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Removing network rails-template_dev
WARNING: Network rails-template_dev not found.
Removing volume rails-template_db-data
ERROR: remove rails-template_db-data: volume is in use - [1cdf1f2dd6022b1093d20fef9b9252fe780a2916cdc2b9f05a092b142ee92278]
```